
#define DEBUG                     1
#define TACDM_NAMESPACING         10


#define TACDM_BASEOFFSET          732
#define TACDM_CLASSPRINTOFFSET    635
#define TACDM_HUDPRINTOFFSET      435

#define TACDM_AUTO_COMMON         TACDM_BASEOFFSET-200

#define TACDM_AUTO_OPEN           TACDM_BASEOFFSET-100
#define TACDM_AUTO_ENTER          TACDM_BASEOFFSET-101
#define TACDM_AUTO_DEATH          TACDM_BASEOFFSET-102
#define TACDM_AUTO_RESPAWN        TACDM_BASEOFFSET-103
#define TACDM_AUTO_DISCONNECT     TACDM_BASEOFFSET-104

#define TACDM_CHOOSECLASS         TACDM_BASEOFFSET+1
#define TACDM_PRINTCLASSDESC      TACDM_BASEOFFSET+2
#define TACDM_SETUPCLASS          TACDM_BASEOFFSET+3
#define TACDM_HUD                 TACDM_BASEOFFSET+4

#define TACDM_ADDMONEY            TACDM_BASEOFFSET+5
#define TACDM_TAKEMONEY           TACDM_BASEOFFSET+6
#define TACDM_PAYFORKILL          TACDM_BASEOFFSET+7

#define TACDM_INTERNAL_CHANGEMONEY TACDM_BASEOFFSET+55
